#%RAML 1.0 Trait

queryParameters:
  companyName:
    displayName: Company Name 
    description: Returns records that match's the company name       
    required: false
    type: string
    example: "FastGo"