http:
  listener:
    host: "0.0.0.0"
    port: "9085"

  requester:
    travelOnTip:
      host: "localhost"
      port: "9083"
      routes_path: "/TravelOnTip/routes"
      schedules_path: "/TravelOnTip/schedules"

    fastGo:
      host: "localhost"
      port: "9084"
      routes_path: "/FastGo/routes"
      schedules_path: "/FastGo/schedules"